services:
  swifty-backend:
    depends_on:
      - db
    build: .
    ports:
      - "3333:3000"
    networks:
      - bridged-network
    command: npm run start:dev
    environment:
      - DATABASE_URL=postgres://admin:admin@db:5432/swifty
    develop:
      watch:
        - path: ./
          target: /app # same as the WORKDIR of NestJS Dockerfile
          action: sync
        - path: ./package.json
          action: rebuild
        - path: ./package-lock.json
          action: rebuild

  db: # This will also be the domain name of that service
    image: postgres
    ports:
      - "5432:5432"
    networks:
      - bridged-network
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: swifty # default db
    volumes:
      - db-data:/var/lib/postgresql/data

  pgadmin:
    depends_on:
      - db
    image: dpage/pgadmin4
    ports:
      - "5050:80"
    networks:
      - bridged-network
    environment:
      PGADMIN_DEFAULT_EMAIL: email@email.com
      PGADMIN_DEFAULT_PASSWORD: password
    volumes:
      - pgadmin-data:/var/lib/pgadmin

volumes:
  db-data:
  pgadmin-data:

networks:
  bridged-network:
    driver: bridge